server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://164.92.70.172:3315/securesign?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: natujenge
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#springdoc:
#  swagger-ui:
#    enabled: true
#    version: 3.0